### ISSUE TITLE
FRI 3.0 / Sunrise 2.7

### ISSUE THREAD

**Issue by mhubii** [KCL-BMEIS/fri#29]
There appears to be a connection issue when compiling `fri-2.7` branch. The source for the error is currently unclear.

The error message can be found here: https://github.com/lbr-stack/lbr_fri_ros2_stack/issues/181#issuecomment-2140872149

## Proposed approach
Compile without cmake, simply using make:

1. Go to
```shell
cd <path_to>/FRI-Client-SDK_Cpp/build/GNUMake
```

2. Build
```shell
make
```

3. Run
```shell
cd <path_to>/FRI-Client-SDK_Cpp/example/LBRJointSineOverlay
./LBRJointSineOverlay
```

If you could test this @OmidRezayof, would be awesome! But don't worry.

## Related documentation
Source documentation:
![fri_2 7](https://github.com/lbr-stack/fri/assets/26366414/64f5b2be-1a7c-45fd-bff2-85335836eea3)

PDF documentation:
![Screenshot from 2024-05-31 09-37-32](https://github.com/lbr-stack/fri/assets/26366414/bb414671-1fd1-430d-8132-cda23278ad20)

## TODO
- [ ] Change branch `2.7` -> `3.0`
- [ ] In CMake, check for `2.7`, although on branch `3.0`
- [ ] Update repos in https://github.com/lbr-stack/lbr_fri_ros2_stack/
- [ ] Update README here
